server:
  port: 8090
spring:
  datasource:
    druid:
      jamesDB:
        url: jdbc:mysql://127.0.0.1:3306/distribute1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
        username: root
        password: 12345678
      peterDB:
        url: jdbc:mysql://127.0.0.1:3306/distribute2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
        username: root
        password: 12345678
  #jta相关参数配置
  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager
  