server:
  port: 8090
spring:
  application:
    name: lcn-busi
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/distribute1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
zookeeper:
  url: zookeeper://127.0.0.1:2181
dubbo:
  name: lcn-busi
  port: 20880

