server:
  port: 5003
spring:
  application:
    name: seata-busi
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/distribute2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
tx-seata:
  applicationId: enjoy-busi
  txServiceGroup: enjoy-tx-group
zookeeper:
  url: zookeeper://127.0.0.1:2181
dubbo:
  name: seata-busi
  port: 20881